# Generated by Django 3.0.5 on 2020-06-01 12:26

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("wagtailimages", "0001_squashed_0021"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudiesListingPage",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseStudyGuidelinesSectionTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseStudyPage",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
                ("introduction", models.CharField(max_length=240)),
                ("header_image_description", models.CharField(max_length=240)),
                ("publication_date", models.DateField()),
                ("collaborator", models.CharField(max_length=120)),
                ("read_time", models.IntegerField(help_text="Time taken (in minutes) to read the case study")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("hide_horizontal_rule", wagtail.blocks.BooleanBlock(required=False)),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                            (
                                "quote_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Quote section title, max length 120 characters",
                                                max_length=120,
                                            ),
                                        ),
                                        ("hide_horizontal_rule", wagtail.blocks.BooleanBlock(required=False)),
                                        ("content_top", wagtail.blocks.RichTextBlock()),
                                        ("quote", wagtail.blocks.CharBlock(help_text="Quote", max_length=300)),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                        ),
                                        ("content_bottom", wagtail.blocks.RichTextBlock(required=False)),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        help_text="Image dimensions should be 1912px wide\u200a×\u200a714px high",  # noqa: RUF001
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "section_tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="case_studies.CaseStudyGuidelinesSectionTag",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="casestudyguidelinessectiontag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_study_section_items",
                to="case_studies.CaseStudyPage",
            ),
        ),
        migrations.AddField(
            model_name="casestudyguidelinessectiontag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_studies_casestudyguidelinessectiontag_items",
                to="taggit.Tag",
            ),
        ),
    ]
