# Generated by Django 3.2.25 on 2026-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_studies", "0004_auto_20201012_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudyguidelinessectiontag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
