# Generated by Django 4.2.30 on 2026-07-05 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("case_studies", "0008_alter_casestudypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudyguidelinessectiontag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
    ]
