# Generated by Django 3.0.5 on 2020-04-23 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0002_auto_20200423_1311"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailtrans", "0009_create_initial_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("guidelines", "0001_squashed_0004_auto_20200422_1351"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GuidelinePage",
            new_name="GuidancePage",
        ),
    ]
