# Generated by Django 3.2.25 on 2026-07-05 02:07

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guidelines", "0011_drop_translatablepage_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidancepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "dos_and_donts",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Do's and dont's title", max_length=200)),
                                (
                                    "dos",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [("item", wagtail.blocks.CharBlock(help_text="Item text", max_length=250))]
                                        )
                                    ),
                                ),
                                (
                                    "donts",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [("item", wagtail.blocks.CharBlock(help_text="Item text", max_length=250))]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="guidelineslistingpage",
            name="information_banners",
            field=wagtail.fields.StreamField(
                [
                    (
                        "information_banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Banner heading, max length 120 characters", max_length=120
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=("bold", "italic", "link", "document-link", "hr", "ul", "ol")
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
