# Generated by Django 5.2.15 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guidelines", "0012_auto_20260705_0207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidelinessectionpage",
            name="landing_page_summary",
            field=models.CharField(
                default="", help_text="Text to be shown on the guidelines landing page", max_length=240
            ),
            preserve_default=False,
        ),
    ]
