FROM nikolaik/python-nodejs:python3.11-nodejs22 AS build-stage

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /workdir

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=production
ENV DJANGO_ENV=production

RUN npx gulp build
RUN python manage.py collectstatic --noinput -v2

FROM nginxinc/nginx-unprivileged:latest AS production-stage
USER root
COPY --from=build-stage --chown=nginx:root /workdir/static /usr/share/nginx/html/static
COPY --chown=nginx:root default.conf /etc/nginx/conf.d/default.conf
USER nginx
