# https://pnpm.io/settings
minimumReleaseAge: 10080
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1
  - ua-parser-js@1.0.41
allowBuilds:
  '@parcel/watcher': false # via gulp/browser-sync (prebuilt binary is used)
  es5-ext: false # via browser-sync
