# Generated by Django 3.2.25 on 2026-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0003_auto_20200519_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmodule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="moreinformationmodule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="orderablelinks",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
