# Generated by Django 5.2.15 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modules", "0004_auto_20260705_0022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmodule",
            name="admin_title",
            field=models.CharField(default="", help_text="Title to appear in the admin area", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="linksmodule",
            name="title",
            field=models.CharField(default="", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moreinformationmodule",
            name="admin_title",
            field=models.CharField(default="", help_text="Title to appear in the admin area", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moreinformationmodule",
            name="title",
            field=models.CharField(default="", max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderablelinks",
            name="url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
