# Generated by Django 3.0.5 on 2020-05-27 09:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0003_auto_20200427_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancepage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
