# Generated by Django 3.0.7 on 2020-10-12 13:30

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_studies", "0003_auto_20200623_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudypage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "simple_rich_text_section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "description",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Non visible description, max length 120 characters, used for html id.",
                                        max_length=120,
                                    ),
                                ),
                                ("content", wagtail.core.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "quote_section",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("quote", wagtail.core.blocks.CharBlock(help_text="Quote", max_length=300)),
                                (
                                    "attribution",
                                    wagtail.core.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
