# Generated by Django 3.0.5 on 2020-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "LA Spanish"), ("id", "Bahasa")], max_length=100
            ),
        ),
    ]
