# Generated by Django 3.2.25 on 2026-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0005_auto_20200729_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="sponsoritem",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
