# Generated by Django 3.2.25 on 2026-07-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("sponsors", "0007_collapse_translatablepage_mti"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorspage",
            name="translatablepage_ptr",
        ),
        migrations.AlterField(
            model_name="sponsorspage",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
        ),
    ]
