# Generated by Django 3.2.25 on 2026-07-05 02:07

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0008_drop_translatablepage_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "sponsors_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ],
                            template="streams/sponsors_block.html",
                        ),
                    ),
                    (
                        "supports_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(help_text="Do's and dont's title", max_length=200)),
                                ("introduction", wagtail.blocks.RichTextBlock()),
                                (
                                    "logos",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "logo",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        help_text="Logo of supporter", required=True
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="URL of supporter", max_length=250
                                                    ),
                                                ),
                                                (
                                                    "logo_description",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Alt description for the image", max_length=250
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
