# Generated by Django 5.2.15 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0009_alter_sponsorspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsoritem",
            name="logo_description",
            field=models.CharField(
                blank=True, default="", help_text="Alt tag description for sponsor logo", max_length=240
            ),
            preserve_default=False,
        ),
    ]
