# Generated by Django 3.0.5 on 2020-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genericpagewithsubnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='masthead_image_description',
            field=models.CharField(blank=True, help_text='Alt tag description for image', max_length=240, null=True),
        ),
    ]
