# Generated by Django 3.0.5 on 2020-04-07 15:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(choices=[("en", "en"), ("es", "es"), ("id", "id")], max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("introduction", wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SponsorItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(blank=True, help_text="Title", max_length=140)),
                ("url", models.URLField(blank=True, help_text="Enter URL")),
                (
                    "logo",
                    models.ForeignKey(
                        help_text="Sponsor image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "sponsor",
                    modelcluster.fields.ParentalKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_items",
                        to="sponsors.Sponsor",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
