# Generated by Django 3.0.5 on 2020-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_mainmenu_phase_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermenu',
            name='translation_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SponsorItem',
        ),
    ]
