# Generated by Django 3.0.5 on 2020-06-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_auto_20200618_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='logo_description',
        ),
    ]
