# Generated by Django 3.0.5 on 2020-05-13 08:32

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("wagtailimages", "0001_squashed_0021"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "masthead_title",
                    models.CharField(help_text="Title for masthead component", max_length=240, null=True),
                ),
                ("masthead_description", wagtail.fields.RichTextField(blank=True, default="")),
                (
                    "masthead_link_title",
                    models.CharField(blank=True, help_text="Title for link", max_length=240, null=True),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "content_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "masthead_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
                (
                    "masthead_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
