# Generated by Django 3.0.5 on 2020-05-15 14:54

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericPageWithSubNav",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "navigation_title",
                    models.CharField(blank=True, help_text="Title for Navigation", max_length=120, null=True),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "rich_text_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                            (
                                "quote_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Quote section title, max length 120 characters",
                                                max_length=120,
                                            ),
                                        ),
                                        ("content_top", wagtail.blocks.RichTextBlock()),
                                        ("quote", wagtail.blocks.CharBlock(help_text="Quote", max_length=300)),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                        ),
                                        ("content_bottom", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
