# Generated by Django 3.0.5 on 2020-06-03 15:56

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_auto_20200528_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters",
                                        max_length=120,
                                        required=False,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("full", "Full Width"), ("half", "Half Width")]
                                    ),
                                ),
                                (
                                    "text_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("centre", "Centred"), ("right", "Right")]
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "highlight_list_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                (
                                    "items_list",
                                    wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label="Item")),
                                ),
                            ]
                        ),
                    ),
                    (
                        "case_study_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                (
                                    "text_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("centre", "Centred"), ("right", "Right")]
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text for button", max_length=120, required=False
                                    ),
                                ),
                                ("button_link", wagtail.blocks.PageChooserBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
