# Generated by Django 3.0.5 on 2020-06-15 14:06

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_auto_20200603_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpagewithsubnav",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("hide_horizontal_rule", wagtail.blocks.BooleanBlock(required=False)),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "quote_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.CharBlock(help_text="Quote", max_length=300)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
