# Generated by Django 3.0.5 on 2020-07-08 10:58

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_auto_20200623_1404"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookiePage",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True, default="")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "cookie_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                        ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                                    ]
                                ),
                            ),
                            (
                                "Analtyics_cookie_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                        ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                                    ],
                                    template="streams/analytics_cookie_block.html",
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
