# Generated by Django 3.0.5 on 2020-07-13 12:43

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_cookiepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericPage",
            fields=[
                (
                    "translatablepage_ptr",
                    models.IntegerField(
                        auto_created=True, db_column="translatablepage_ptr_id", primary_key=True, serialize=False
                    ),
                ),
                ("introduction", wagtail.core.fields.RichTextField(blank=True, default="")),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "rich_text_section",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Section title, max length 120 characters", max_length=120
                                            ),
                                        ),
                                        ("content", wagtail.core.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                            (
                                "quote_section",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("quote", wagtail.core.blocks.CharBlock(help_text="Quote", max_length=300)),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Quote attribution", max_length=120
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
