# Generated by Django 3.2.25 on 2026-07-05 02:07

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_drop_wagtailtrans_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "quote_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.CharBlock(help_text="Quote", max_length=300)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericpagewithsubnav",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "quote_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.CharBlock(help_text="Quote", max_length=300)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(help_text="Quote attribution", max_length=120),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "rich_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters",
                                        max_length=120,
                                        required=False,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("full", "Full Width"),
                                            ("half", "Half Width"),
                                            ("two-thirds", "Two Thirds"),
                                        ]
                                    ),
                                ),
                                (
                                    "text_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("centre", "Centred"), ("right", "Right")]
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "highlight_list_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                ("items_list", wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label="Item"))),
                            ]
                        ),
                    ),
                    (
                        "case_study_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters", max_length=120
                                    ),
                                ),
                                (
                                    "text_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("centre", "Centred"), ("right", "Right")]
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Text for button", max_length=120, required=False
                                    ),
                                ),
                                ("button_link", wagtail.blocks.PageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "sponsors_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section title, max length 120 characters",
                                        max_length=120,
                                        required=False,
                                    ),
                                ),
                                (
                                    "width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("full", "Full Width"),
                                            ("half", "Half Width"),
                                            ("two-thirds", "Two Thirds"),
                                        ]
                                    ),
                                ),
                                (
                                    "text_alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("centre", "Centred"), ("right", "Right")]
                                    ),
                                ),
                                ("content", wagtail.blocks.RichTextBlock(required=False)),
                            ],
                            template="streams/homepage_sponsors_block.html",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
