# Generated by Django 5.2.15 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_auto_20260705_0207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpagewithsubnav",
            name="navigation_title",
            field=models.CharField(blank=True, default="", help_text="Title for Navigation", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="masthead_image_description",
            field=models.CharField(blank=True, default="", help_text="Alt tag description for image", max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="masthead_link_title",
            field=models.CharField(blank=True, default="", help_text="Title for link", max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="masthead_title",
            field=models.CharField(blank=True, default="", help_text="Title for masthead component", max_length=240),
            preserve_default=False,
        ),
    ]
