# Generated by Django 3.1.14 on 2025-01-08 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0008_footermenu_quick_links_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainmenu",
            name="cookie_banner_button_text",
        ),
        migrations.RemoveField(
            model_name="mainmenu",
            name="cookie_banner_description",
        ),
        migrations.RemoveField(
            model_name="mainmenu",
            name="cookie_banner_preferences_link_text",
        ),
        migrations.RemoveField(
            model_name="mainmenu",
            name="cookie_banner_title",
        ),
        migrations.RemoveField(
            model_name="mainmenu",
            name="cookie_page",
        ),
    ]
