# Generated by Django 3.2.25 on 2026-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0009_auto_20250108_0602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footermenu",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
