# Generated by Django 5.2.15 on 2026-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0010_auto_20260705_0022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footermenu",
            name="admin_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="footermenu",
            name="quick_links_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="footermenu",
            name="sponsors_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="footermenu",
            name="translation_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="admin_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
