# Generated by Django 5.2.15 on 2026-07-23 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0011_alter_footermenu_admin_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainmenu",
            name="phase_banner_description",
        ),
    ]
