# Generated by Django 5.2.16 on 2026-08-12 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0012_remove_mainmenu_phase_banner_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainmenu",
            name="button_aria_label",
        ),
    ]
